### ISSUE TITLE
remove broken files

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/sip-feedstock#28]
@isuruf I'm investigating the broken packages on windows due to the bad prefix to see if we can fix `qgis` and `pdal` builds but I'm not sure anymore if this is the main problem. The offending line in the `sip` packages are in the same file as `pyqt` (Lib/site-packages/sipconfig.py), see https://github.com/conda-forge/pyqt-feedstock/issues/82, there I found:

```
'sip_config_args':    '--sysroot=D:\\bld\\sip_1572710327910\\_h_env --bindir=D:\\bld\\sip_1572710327910\\_h_env\\Library\\bin',
```

Which look wrong but the problem is that when I tried to see what version was OK I got as far as `sip-4.18.1`! So either tons of packages are broken or this used to work at some point.

BTW `4.18`, the first one, seems to have a bad prefix but it is:

```
    'sip_bin':            'C:\\Miniconda-x64\\envs\\_build\\Library\\bin\\sip',
    'sip_config_args':    '--sysroot=C:\\Miniconda-x64\\envs\\_build --bindir=C:\\Miniconda-x64\\envs\\_build\\Library\\bin',
```

Am I looking at the wrong place?

xref.: https://github.com/conda-forge/qgis-feedstock/pull/124

**Comment by isuruf** [comment]
You are looking at the correct place. It looks like `sip` has been broken for a while. I'm not sure how qgis worked before

**Comment by ocefpaf** [comment]
> You are looking at the correct place. It looks like `sip` has been broken for a while. I'm not sure how qgis worked before

Also, the remaining `pyqt` still have those. I'm quite confused now :-/

**Comment by isuruf** [comment]
Ah, you need to look `info/paths.json` to see if it is recorded there or not

**Comment by isuruf** [comment]
4.19.20 is the last working version.

**Comment by ocefpaf** [comment]
Thanks! For a moment there I was scared that everything was brokenly working and we were fixingly breaking them :smile:

**Comment by isuruf** [comment]
4.19.24 is marked broken in https://github.com/conda-forge/admin-requests/pull/111
